=== BKonopka123/AGH_sem5/Ti/techniki_internetowe/lab2/zad1_dtd.dtd
<!DOCTYPE biblioteka [
<!ELEMENT biblioteka (dzial+)>
<!ELEMENT dzial (nazwa, ksiazka+)>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT ksiazka (autor1?, autor2?, tytul, cena)>
<!ELEMENT autor1 (imie, nazwisko)>
<!ELEMENT imie (#PCDATA)>
<!ELEMENT nazwisko (#PCDATA)>
<!ELEMENT tytul (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ELEMENT autor2 (imie, nazwisko)>
]>

=== BKonopka123/AGH_sem5/Ti/techniki_internetowe/lab3/zad1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteka SYSTEM "zad1_dtd.dtd">
<?xml-stylesheet type="text/css" href="data.css"?>

<biblioteka xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="zad1_schema.xsd">

  <dzial>
  
    <nazwa>
      Nauka
    </nazwa>
    


    <elementt1>
    <ksiazka>
      
            <tytul>
        Podstawy Fizyki 1
      </tytul>


      <autor1>
        <imie>
          David
        </imie>
        <nazwisko>
          Holliday
        </nazwisko>
      </autor1>
      
      <autor2>
        <imie>
          Robert
        </imie>
        <nazwisko>
          Resnick
        </nazwisko>
      </autor2>

      <cena>
        100
      </cena>

      
      
    </ksiazka>
    </elementt1>

    <elementt2>
    <ksiazka>

          <tytul>
      Szkola programowania C
      </tytul>
      
      <autor1>
        <imie>
          Stephen
        </imie>
        <nazwisko>
        Prata
        </nazwisko>
      </autor1>
      
         <cena>
          100
      </cena>
      

    </ksiazka>
    </elementt2>

        <elementt1>
    <ksiazka>

          <tytul>
      Podstawy fizyki 2
      </tytul>
      
      <autor1>
        <imie>
          David
        </imie>
        <nazwisko>
          Holliday
        </nazwisko>
      </autor1>
      
      <autor2>
        <imie>
          Robert
        </imie>
        <nazwisko>
          Resnick
        </nazwisko>
      </autor2>

               <cena>
          100
      </cena>
    

    </ksiazka>
    </elementt1>

  </dzial>

  <dzial>
  
    <nazwa>
    Dla dzieci
    </nazwa>
    
    <elementt1>
    <ksiazka>
      
            
      <tytul>
      Kubus puchatek
      </tytul>

      <autor1>
        <imie>
          Alan Alexander
        </imie>
        <nazwisko>
          Milne
        </nazwisko>
      </autor1>


               <cena>
          100
      </cena>

        
 
    </ksiazka>
    </elementt1>

        <elementt2>
    <ksiazka>
      
            
      <tytul>
      Podroze Pana kleksa
      </tytul>

      <autor1>
        <imie>
          Jan
        </imie>
        <nazwisko>
          Brzechwa
        </nazwisko>
      </autor1>

                 <cena>
          100
      </cena>
 
    </ksiazka>
    </elementt2>

        <elementt1>
    <ksiazka>
      
            
      <tytul>
      Przygody alicji w krainie czarow
      </tytul>

      <autor1>
        <imie>
          Lewis
        </imie>
        <nazwisko>
          Carrol
        </nazwisko>
      </autor1>

                 <cena>
          100
      </cena>
 
    </ksiazka>
    </elementt1>

        <elementt2>
    <ksiazka>
      
            
      <tytul>
      Akademia Pana Kleksa
      </tytul>

      <autor1>
        <imie>
          Jan
        </imie>
        <nazwisko>
          Brzechwa
        </nazwisko>
      </autor1>

                 <cena>
          100
      </cena>
 
    </ksiazka>
    </elementt2>
  </dzial>
  
</biblioteka>

=== BKonopka123/AGH_sem5/Ti/techniki_internetowe/lab2/zad1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="data.css"?>
<!DOCTYPE biblioteka SYSTEM "/home/stud2021/1konopka/public_html/techniki_internetowe/lab2/zad1_dtd.dtd">

<biblioteka xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/home/stud2021/1konopka/public_html/techniki_internetowe/lab2/zad1_schema.xsd">

  <dzial>
  
    <nazwa>
      Fantastyka
    </nazwa>
    
    <ksiazka>
      
      <autor1>
        <imie>
          Adam
        </imie>
        <nazwisko>
            Malysz
        </nazwisko>
      </autor1>
      
      <tytul>
        Abcdef
      </tytul>
      
      <cena>
        120
      </cena>
      
    </ksiazka>
    
    <ksiazka>
      
      <autor1>
        <imie>
          Janusz
        </imie>
        <nazwisko>
        Pudzianowski
        </nazwisko>
      </autor1>
      
        <autor2>
        <imie>
          John
        </imie>
        <nazwisko>
          Malloy
        </nazwisko>
      </autor2>
      
      <tytul>
      Ghijklm
      </tytul>
      
      <cena>
        150
      </cena>
      
    </ksiazka>
    
  </dzial>

  <dzial>
  
    <nazwa>
    Horror
    </nazwa>
    
    <ksiazka>
      
      <autor1>
        <imie>
          Dorota
        </imie>
        <nazwisko>
          Wellman
        </nazwisko>
      </autor1>
      
      <tytul>
      adwewewe
      </tytul>
        
      <cena>
           90
      </cena>
  
    </ksiazka>
    
  </dzial>

  <dzial>
  
    <nazwa>
      Kryminal
    </nazwa>
    
    <ksiazka>
      
      
      <tytul>
        fdgrgbcbvtfb
      </tytul>
      
      <cena>
        80
      </cena>
      
    </ksiazka>
    
  </dzial>
  
</biblioteka>
